# Generated by Django 5.1.7 on 2025-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
